[project]
name = "bad-roblox-asset-texture-taker"
version = "0.1.0"
description = "Tool for downloading Roblox catalog item textures via Roblox's API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi==2025.6.15",
    "charset-normalizer==3.4.2",
    "idna==3.10",
    "pillow>=11.3.0",
    "requests==2.32.4",
    "rich>=14.0.0",
    "urllib3==2.5.0",
]
